name: Build and Upload Binaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build for Windows 32_64-bit
  build-windows:
    runs-on: windows-latest
    name: Build for Windows (x86 & x64)
    strategy:
      matrix:
        arch: [x86, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Configure CMake (Release)
        run: cmake -G "Ninja" -B build/${{ matrix.arch }}/release -DCMAKE_BUILD_TYPE=Release

      - name: Build (Release)
        run: cmake --build build/${{ matrix.arch }}/release

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ResMan_win${{ matrix.arch }}
          path: build/${{ matrix.arch }}/release/*

  # Build for Linux 32-bit
  build-linux32:
    runs-on: ubuntu-latest
    name: Build for Linux32
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential gcc-multilib g++-multilib

      - name: Build project
        run: |
          mkdir build && cd build
          cmake -DCMAKE_CXX_FLAGS="-m32" ..
          make

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ResMan_linux_32
          path: build/*

  # Build for Linux 64-bit
  build-linux64:
    runs-on: ubuntu-latest
    name: Build for Linux64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build project
        run: |
          mkdir build && cd build
          cmake ..
          make

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ResMan_linux_64
          path: build/*
