name: Publish Release 

on:
  # Triggers the workflow on push or pull request events but only for the "development" branch
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Release creation
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read   # Needed for downloading artifacts
    steps:
      - name: Validate Tag Format
        run: |
          if [[ ! "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format!"
            exit 1
          fi

      - name: Download all artifacts
        uses: dawidd6/action-download-artifact@v9
        with:
          path: artifact
          merge_multiple: true
          workflow: Build.yml
          github_token: ${{secrets.GITHUB_TOKEN}}
          repo: ${{ github.repository }}
          use_unzip: true
          workflow_conclusion: success

      - name: List Unzipped Files (Debug)
        run: find ./artifact -type f -name "ResMan-*"

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "ResMan ${{ github.ref_name }}"
          body: "Pre-built binaries for ResMan ${{ github.ref_name }}"
          files: |
            artifact/**/ResMan*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}