name: Publish Release 

on:
  push:
    tags:
      - "v*"

jobs:
  # Release creation
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Validate Tag Format
        run: |
          if [[ ! "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format!"
            exit 1
          fi

      - name: Download all artifacts
        uses: dawidd6/action-download-artifact@v9
        with:
          path: artifact
          merge_multiple: true
          workflow: Build.yml
          github_token: ${{secrets.GITHUB_TOKEN}}
          repo: ${{ github.repository }}
          use_unzip: true
          workflow_conclusion: success

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "ResMan ${{ github.ref_name }}"
          body: "Pre-built binaries for ResMan ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: List Unzipped Files (Debug)
        run: find ./artifact -type f -name "ResMan-*"

      - name: Upload Release Assets
        uses: AButler/upload-release-assets@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: ${{ github.ref_name }}
          name: "ResMan ${{ github.ref_name }}"
          body: "Pre-built binaries for ResMan ${{ github.ref_name }}"
          files: |
            artifact/**/ResMan*  # Uploads all matching files recursively
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}